"""`dotinfra index`: the generated INDEX.md inventory."""

from __future__ import annotations

from pathlib import Path

from .context import get_context
from .model import FOLDERS, Component, load_cmdb

INDEX_NAME = "INDEX.md"
_COLUMNS = ("id", "status", "address", "role", "tags")


def render_index(components: list[Component], name: str) -> str:
    """INDEX.md content. Deterministic (no timestamps) so `--check` and git stay quiet."""
    lines = [
        f"# {name} — infrastructure index",
        "",
        "<!-- Generated by `dotinfra index`. Do not edit: change the component files. -->",
        "",
        f"{len(components)} component(s). Rules for agents: [AGENTS.md](AGENTS.md).",
    ]
    for kind, folder in FOLDERS.items():
        group = [c for c in components if c.kind == kind]
        if not group:
            continue
        lines += ["", f"## {folder.capitalize()}", "",
                  "| " + " | ".join(_COLUMNS) + " |", "|" + "---|" * len(_COLUMNS)]
        lines += [_row(component) for component in group]
    return "\n".join(lines) + "\n"


def _row(component: Component) -> str:
    cells = (
        f"[{component.id}]({component.rel()})",
        component.status or "?",
        component.address or "",
        str(component.meta.get("role") or ""),
        ", ".join(component.tags),
    )
    return "| " + " | ".join(_cell(cell) for cell in cells) + " |"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def write_index(root: Path, name: str, components: list[Component] | None = None) -> bool:
    """Rewrite INDEX.md; return True when its content changed."""
    content = render_index(load_cmdb(root) if components is None else components, name)
    path = root / INDEX_NAME
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def is_stale(root: Path, name: str) -> bool:
    path = root / INDEX_NAME
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    return current != render_index(load_cmdb(root), name)


def cmd_index(args) -> int:
    ctx = get_context(args)
    name = ctx.config.get("cmdb", "name", "home")
    if args.check:
        if is_stale(ctx.root, name):
            print(f"{INDEX_NAME} is stale; run `dotinfra index`")
            return 1
        print(f"{INDEX_NAME} is up to date")
        return 0
    changed = write_index(ctx.root, name, ctx.components())
    print(f"{'wrote' if changed else 'unchanged'} {ctx.root / INDEX_NAME}")
    return 0


def register(subparsers) -> None:
    parser = subparsers.add_parser(
        "index", help="regenerate INDEX.md",
        description="Rewrite INDEX.md, the generated inventory table of all components.")
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if INDEX.md is out of date")
    parser.set_defaults(func=cmd_index)
