"""`dotinfra ssh-config`: OpenSSH ``Host`` blocks generated from ``ssh:`` frontmatter."""

from __future__ import annotations

import sys
from pathlib import Path

from .context import get_context
from .model import Component

HEADER = """\
# Generated by `dotinfra ssh-config` from the CMDB at {root}.
# Do not edit; change the components' `ssh:` frontmatter and regenerate.
# Use it from ~/.ssh/config with:  Include {include}
"""


def ssh_hosts(components: list[Component]) -> list[Component]:
    """Components that get a Host block: they have ``ssh:`` and are not retired."""
    return [c for c in components
            if c.ssh and c.status != "retired" and (c.ssh.get("host") or c.address)]


def host_block(component: Component, known: set[str]) -> tuple[list[str], list[str]]:
    """Return ``(lines, warnings)`` for one component."""
    ssh = component.ssh
    lines = [f"Host {component.id}", f"    HostName {ssh.get('host') or component.address}"]
    warnings = []
    if ssh.get("user"):
        lines.append(f"    User {ssh['user']}")
    if ssh.get("port"):
        lines.append(f"    Port {ssh['port']}")
    if ssh.get("key"):
        lines += [f"    IdentityFile {ssh['key']}", "    IdentitiesOnly yes"]
    jump = ssh.get("jump")
    if jump:
        if jump in known:
            lines.append(f"    ProxyJump {jump}")
        else:
            warnings.append(f"{component.rel()}: ssh.jump {jump!r} is not a component with ssh:; "
                            "ProxyJump omitted")
    return lines, warnings


def render_ssh_config(components: list[Component], root: Path,
                      include: str = "~/.ssh/config.d/dotinfra") -> tuple[str, list[str]]:
    hosts = ssh_hosts(components)
    known = {c.id for c in hosts}
    out = [HEADER.format(root=root, include=include)]
    warnings: list[str] = []
    for component in hosts:
        unsafe = component.unsafe_values()
        if unsafe:
            known.discard(component.id)
            warnings += [f"{component.rel()}: {field} {reason}; unsafe, Host block omitted"
                         for field, reason in unsafe]
            continue
        lines, block_warnings = host_block(component, known)
        out.append(f"# {component.title} ({component.rel()})\n" + "\n".join(lines) + "\n")
        warnings += block_warnings
    return "\n".join(out), warnings


def cmd_ssh_config(args) -> int:
    ctx = get_context(args)
    include = args.output or "~/.ssh/config.d/dotinfra"
    text, warnings = render_ssh_config(ctx.components(), ctx.root, include)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if args.output:
        path = Path(args.output).expanduser()
        path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        path.write_text(text, encoding="utf-8")
        hosts = sum(line.startswith("Host ") for line in text.splitlines())
        print(f"wrote {hosts} host(s) to {path}")
        print(f"add `Include {args.output}` near the top of ~/.ssh/config if it is not there")
    else:
        sys.stdout.write(text)
    return 0


def register(subparsers) -> None:
    parser = subparsers.add_parser(
        "ssh-config", help="generate ssh_config Host blocks",
        description="Generate OpenSSH Host blocks (HostName, User, Port, IdentityFile, "
                    "ProxyJump from ssh.jump) for every non-retired component with ssh: "
                    "frontmatter.")
    parser.add_argument("--output", "-o", metavar="FILE",
                        help="write to FILE (e.g. ~/.ssh/config.d/dotinfra) instead of stdout")
    parser.set_defaults(func=cmd_ssh_config)
